name: Track changes

on:
  push:
    branches: [new_branch]

jobs:
  track-changes:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get changed files
        run : |
          LAST_COMMIT = $(git rev-parse HEAD)
          URL="https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/${LAST_COMMIT}...${{ github.sha }}"
          CHANGED_FILES=$(curl -L \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer ${{ secrets.CICD_TOKEN }}" \
                            -H "X-Github-Api-Version: 2022-11-28" \
                            $URL | jq -r'files[].filename')
          echo "$CHANGED_FILES" > changed_files.txt
          